### PR TITLE
Support for all Geosupport functions and Parameters

### PR DESCRIPTION
**Pull request by docmarionum1**
This adds support for all Geosupport functions and all parameters to Geosupport (flags, etc.). 

This turned into a major revision with very little of the original architecture remaining.  

Let me know if you have any questions.

### CODE REVIEW

**Comment by ishiland** [comment]
Wow, thanks for this. Did you create the CSVs or source them from somewhere else? I assume with any future changes to the Work Areas in Geosupport, they can be easily updated.  Ill take a look at the rest of it later this week, thanks again.

**Comment by docmarionum1** [comment]
Yes, ease of maintenance was my intention by using CSVs to describe the work areas.  I created them by copying the tables from the online docs, but had to do some manual cleanup as well.

**Comment by docmarionum1** [comment]
A coworker found some issues with python 2.7, so I need to fix that.

**Comment by docmarionum1** [comment]
I fixed all know bugs with my fork.

**Comment by ishiland** [comment]
Thanks, Ill merge and push to pypi this weekend. Will need to bump the version to 1.0.0 before releasing to pypi.

**Pull request merged**
